apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saas

resources:
- namespace.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- middleware-redirect-https.yaml

configMapGenerator:
- envs:
  - runtime-images.env
  name: saas-runtime-images

images:
- name: sim2policy-saas
  newName: cr.eu-north1.nebius.cloud/e00gkhk5kcqp6fej6g/sim2policy-saas
  newTag: 08d992b8ab15
