apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saas-data
  labels:
    app: saas
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
